default: &default
  host: <%= ENV['ELASTICSEARCH_HOST'] || ENV['SEARCHBOX_SSL_URL'] %>

development:
  <<: *default
  prefix: 'development'

test:
  <<: *default
  prefix: 'test'

production:
  <<: *default
  prefix: 'production'
