# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d61a015126045d7c257d0448a5fb559cd32c4c36108ddf782014776452478e561a3b11baf7dfec88d9fb0ceed83211f805c453a31727256250ca9b057fa617f

test:
  secret_key_base: e8d5eed174f4808be063c1a8c0da64fea5dde2dd29535d839ccec71a6268fe286bf44ab40e7863d3590c40bcff2aedd3b02b8405d83dc5a7cc0dfc0cf5e126fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
