---
:concurrency: 6
production:
  :concurrency: 40
:queues:
  - [now, 5]
  - [soon, 4]
  - [later, 2]
  - [eventually, 1]
:schedule:
  CounterCacheResetWorker:
    every: 12h
    queue: later
  AverageRatingUpdateWorker:
    every: 6h
    queue: soon
  RankingUpdateWorker:
    every: 12h
    queue: later
  LibraryEntryLogRemovalWorker:
    every: 24h
    queue: eventually
  UploadRemovalWorker:
    every: 12h
    queue: later
