---
:concurrency: 6
production:
  :concurrency: 40
:queues:
  - [now, 5]
  - [soon, 4]
  - [later, 2]
  - [eventually, 1]
:schedule:
  CounterCacheResetWorker:
    every: 12h
  AverageRatingUpdateWorker:
    every: 6h
  RankingUpdateWorker:
    every: 12h
  LibraryEntryLogRemovalWorker:
    every: 12h
  UploadRemovalWorker:
    every: 12h
