name: Kitsu Test Suite

on: [push, pull_request]

env:
  STREAM_API_KEY: q3k9n9kqk3fb
  STREAM_API_SECRET: vkw87x3p323z6ma75n8dvnse98jrr9gkauf2zfjnzbgjpmm54ssnbync4yhhzugc
  CC_TEST_REPORTER_ID: 5e2172ea5a30b07e172058a3b33dfe08c6354699808e8f3010acc32b1ef41395
  BUNDLE_GITHUB__HTTPS: true
  LOG_LEVEL: warn

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6

    services:
      postgres:
        image: postgres:10
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432/tcp
      redis:
        image: redis
        ports:
          - 6379/tcp
      elasticsearch:
        image: elasticsearch:2
        ports:
          - 9200/tcp

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set Up Test Environment
      env:
        DATABASE_URL: postgresql://postgres@postgres:5432/kitsu_test
        REDIS_URL: redis://redis:6379/1
        ELASTICSEARCH_URL: elasticsearch:9200
      run: |
        bundle exec rake db:create db:schema:load

    - name: Run Tests
      env:
        DATABASE_URL: postgresql://postgres@postgres:${{ job.services.postgres.ports[5432] }}/kitsu_test
        REDIS_URL: redis://redis:${{ job.services.redis.ports[6379] }}/1
        ELASTICSEARCH_URL: elasticsearch:${{ job.services.elasticsearch.ports[9200] }}
      run: |
        bundle exec rspec
